### ISSUE TITLE
Site Configuration Update and Announcement Error Message 

### ISSUE THREAD

**Issue by fjbagley** [timberline-secondary/hackerspace#369]
After selecting images in Site Configuration to use for Studio Tyee, I clicked Update and got this error message ![Capture](https://user-images.githubusercontent.com/37415548/78700731-b12d2f00-78ba-11ea-8014-e52988cd26d4.PNG). 

The images did update and functionality was fine. The error was repeatable with subsequent update button clicks.

**Comment by fjbagley** [comment]
Same error when creating announcement. Announcement was created successfully though.

**Comment by tylerecouture** [comment]
SiteConfig model needs an get_absolute_url() method

**Comment by tylerecouture** [comment]
@fjbagley I fixed the error when you update the Site Configuration (will be pulled soon), but I can't reproduce the Announcements problem.  Can you reproduce it and and provide a copy of the error page here?

**Comment by fjbagley** [comment]
Here is an example:
![image](https://user-images.githubusercontent.com/37415548/78935483-b082cd00-7a61-11ea-91e5-a9a37366cad7.png)
Draft was unchecked. No error when draft was checked. 
This was the error:
![image](https://user-images.githubusercontent.com/37415548/78935604-e58f1f80-7a61-11ea-951c-6d0ece954ccf.png)

**Comment by yujinyuz** [comment]
I'm getting the same error. I believe this is related to celery since this line causes the error

```python
if not new_announcement.draft:
    send_notifications.apply_async(args=[self.request.user, new_announcement.id], queue='default')
```
The error doesn't appear when draft is unchecked since since the send_notification task gets run in the background

**Comment by yujinyuz** [comment]
@tylerecouture I just tried creating an announcement and I'm still getting an error

```
web_1          | kombu.exceptions.EncodeError: <SimpleLazyObject: <User: admin>> is not JSON serializable
```

**Comment by tylerecouture** [comment]
Can you provide the whole stack trace, and what setting for the announcement? Are celery an beat containers running? Did you rebuild them too?

**Comment by tylerecouture** [comment]
Hmm... Actually I think I know what it is. Weird this didn't happen for me!  

I'm giving the user object instead of user.id to celery-beat

Weird that I don't get the same error though and that tests pass. Do the Announcements tests pass for you? Maybe I don't have a test covering this...

**Comment by yujinyuz** [comment]
Yes, I just rebuilt it a while ago and tried creating an announcement.

Tests are passing for me. I also thought it was a python version problem since I was using 3.7 to run the web app in my local. But I also tried using the docker web container and I'm still getting the same error.

Here's a stack trace:

```
Traceback:

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in _reraise_errors
  50.         yield

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in dumps
  221.             payload = encoder(data)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/utils/json.py" in dumps
  70.                   **dict(default_kwargs, **kwargs))

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/__init__.py" in dumps
  238.         **kw).encode(obj)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in encode
  199.         chunks = self.iterencode(o, _one_shot=True)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in iterencode
  257.         return _iterencode(o, 0)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/utils/json.py" in default
  59.             return super(JSONEncoder, self).default(o)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in default
  179.         raise TypeError(f'Object of type {o.__class__.__name__} '

During handling of the above exception (Object of type User is not JSON serializable), another exception occurred:

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/Users/eugene/Sources/hackerspace/src/announcements/views.py" in dispatch
  196.         return super(Create, self).dispatch(*args, **kwargs)

File "/Users/eugene/Sources/hackerspace/src/tenant/views.py" in dispatch
  22.             return super().dispatch(*args, **kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/views/generic/edit.py" in post
  172.         return super().post(request, *args, **kwargs)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/django/views/generic/edit.py" in post
  142.             return self.form_valid(form)

File "/Users/eugene/Sources/hackerspace/src/announcements/views.py" in form_valid
  175.             send_notifications.apply_async(args=[self.request.user, new_announcement.id], queue='default')

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/tenant_schemas_celery/task.py" in apply_async
  59.         return super(TenantTask, self).apply_async(args, kwargs, *arg, **kw)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/celery/app/task.py" in apply_async
  568.                 **options

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/celery/app/base.py" in send_task
  775.                 amqp.send_task_message(P, name, message, **options)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/celery/app/amqp.py" in send_task_message
  559.                 **properties

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/messaging.py" in publish
  169.             compression, headers)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/messaging.py" in _prepare
  252.              body) = dumps(body, serializer=serializer)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in dumps
  221.             payload = encoder(data)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/contextlib.py" in __exit__
  130.                 self.gen.throw(type, value, traceback)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in _reraise_errors
  54.         reraise(wrapper, wrapper(exc), sys.exc_info()[2])

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/vine/five.py" in reraise
  194.             raise value.with_traceback(tb)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in _reraise_errors
  50.         yield

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/serialization.py" in dumps
  221.             payload = encoder(data)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/utils/json.py" in dumps
  70.                   **dict(default_kwargs, **kwargs))

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/__init__.py" in dumps
  238.         **kw).encode(obj)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in encode
  199.         chunks = self.iterencode(o, _one_shot=True)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in iterencode
  257.         return _iterencode(o, 0)

File "/Users/eugene/.pyenv/versions/hackerspace/lib/python3.7/site-packages/kombu/utils/json.py" in default
  59.             return super(JSONEncoder, self).default(o)

File "/Users/eugene/.pyenv/versions/3.7.6/lib/python3.7/json/encoder.py" in default
  179.         raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: EncodeError at /announcements/create/
Exception Value: Object of type User is not JSON serializable
```

![Kapture 2020-04-19 at 23 17 47](https://user-images.githubusercontent.com/10972027/79691793-122e0d00-8294-11ea-8de4-8b3ab4eb7c9e.gif)

**Comment by tylerecouture** [comment]
I think the problem is here:
`send_notifications.apply_async(args=[self.request.user, new_announcement.id], queue='default')`

since celery args need to be json serializable, need to refactor to pass `self.request.user.id` instead of the `user` object itself. Not sure if there are down stream effects to this (might need to get the user object back on the other side)

**Comment by yujinyuz** [comment]
Ahh. That makes sense.

I just tried changing it to `self.request.user.id` and it's working now!
